baseURL = 'https://kampannahlavu.cz/'
languageCode = 'cs'
title = '#kampaňnahlavu'
theme = 'ananke'

SectionPagesMenu = "main"
defaultContentLanguage = "cs"

[Languages]
[Languages.cs]
title = "#kampaňnahlavu"
weight = 1
languageName = "Čeština"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Neoficiální fanpage nejbizarnější politické kampaně"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  featured_image = "/kampan-na-hlavu.jpg"
  recent_posts_number = 2
